baseURL = "https://tonguechaude.github.io/"
languageCode = 'fr'
title = 'Portfolio de Tongue-chaude'
theme = "github-style"

publishDir = "public"

pygmentsCodeFences = true
pygmentsUseClasses = true

enableGitInfo = true

[params]
  author = "Tonguechaude"
  description = "Je suis actuellement étudiant en BUT 2 informatique passioné 🤩"
  github = "tonguechaude"
  linkedin = "evan challias"
  email = "tonguefroide@gmail.com"
  url = "https://tonguechaude.servehttp.com"
  keywords = "portfolio"
  #rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "images/github.png"
  avatar = "images/kaarism.jpeg"
  headerIcon = "/images/github-mark-white.png"
  location = "France"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[[params.links]]
    title = "Link2"
    href = "https://tonguechaude.servehttp.com"
    icon = "images/kaarism.jpeg"
